### ISSUE TITLE
Consider allowing naming both directed and the resulting implicit inverse relation

### ISSUE THREAD

**Issue by shapr** [cdsmith/edgy#14]
For example, `DefDirected (DataNode "Room") "population" Many (DataNode "Player")` has an implicit inverse relation, we could call it a Player's "location".

If the name of both the explicit forward and the implicit inverse relation could be specified, might be handy?

`DefDirected (DataNode "Room") "population" "location" Many (DataNode "Player")` would work, does that imply the inverse relation should be explicitly created, and no longer implicit?

**Comment by cdsmith** [comment]
Adding notes from our conversation on this:

Doing this would essentially eliminate the `Inverse` constructor from `RelationId`.  Instead, all directed relations would have a name in both directions.  The advantages are:

1. It just reads better.  Thinking about "the player's location" is much less mind-twisty than thinking about "the inverse relation of the population of the room".
2. If allows mutating the relation in both directions, which can actually be more clear.  For example, one can write `setRelated @"location" player room` instead of *both* `addRelated @"population room player` *and* `removeRelated @"population" oldRoom player`.  Saves even more code if you would have had to look up the old room!

The disadvantage is that there are now double the number of relation names for directed relations.  However, we can do something to mitigate this: now that a name is specific to a direction, it makes sense to scope relation names to only the source `NodeType`.  That is, many different node types can have a relation called "location".  That made less sense when the same name was used for both directions, but now it makes perfect sense.

**Comment by cdsmith** [comment]
Done
